tasks:
  - init: echo -e "\033[0;31mIMPORTANT! \033[1;33mAFTER FINISHING YOUR WORK, PLEASE PUT ALL THE FILES TO \"bin/packaged.js\", USE A JS MINIMIZER/MINIFIER/COMPRESSOR TOOL TO \"COMPILE\" THAT SCRIPT AND PUT YOUR RESULTS IN \"bin/node.js\" \"bin/c.js\" FILE\033[0;37m, WHICH STANDS FOR \"compressed.js\".\033[0m"
image:
  file: .gitpod.Dockerfile