tasks:
  - init: echo -e "\033[0;31mIMPORTANT! \033[1;33mAFTER FINISHING YOUR WORK, PLEASE USE A JS MINIMIZER TOOL TO \"COMPILE\" THE SCRIPT AND PUT YOUR RESULTS IN \"c.sj\" file\033[0;37m, WHICH STANDS FOR \"compressed.js\".\033[0m"
image:
  file: .gitpod.Dockerfile
